# Generated by Django 4.0.4 on 2022-05-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_auto_20210502_0716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enclosure',
            name='post',
        ),
        migrations.DeleteModel(
            name='WebProxy',
        ),
        migrations.RemoveField(
            model_name='source',
            name='is_cloudflare',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='Enclosure',
        ),
    ]
