# Generated by Django 3.1.7 on 2022-05-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_remove_enclosure_post_delete_webproxy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='etag',
        ),
        migrations.RemoveField(
            model_name='source',
            name='site_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='source',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
