# Generated by Django 3.1.7 on 2022-05-11 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0011_auto_20220510_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='interval',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_302_start',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_302_url',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_change',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_polled',
        ),
        migrations.RemoveField(
            model_name='source',
            name='last_success',
        ),
        migrations.RemoveField(
            model_name='source',
            name='status_code',
        ),
        migrations.AddField(
            model_name='source',
            name='num_of_failed_polls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='last_result',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL),
        ),
    ]
