# Generated by Django 3.1.7 on 2022-05-11 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_auto_20220512_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='due_poll',
        ),
    ]
