# Generated by Django 3.1.7 on 2022-05-11 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_remove_source_due_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='next_poll',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
