# Generated by Django 3.1.7 on 2022-05-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0014_source_next_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
