# Generated by Django 3.1.7 on 2022-05-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphql_api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
